version: '3.8'
services:
  db:
    image: postgres:13
    env_file:
      - ../backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data_bewise/
  backend:
    build: 
      context: ../
      dockerfile: ./backend/Dockerfile
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
volumes:
  postgres_data:
